version: '3.9'

services:
  rmq:
    build: 
      context: ./${PATH_RMQ}
      dockerfile: Dockerfile
    ports:
      - "15671:15671"
      - "15672:15672"
      - "5671:5671"
      - "5672:5672"
    environment:
      listeners.ssl.default = 5671

      ssl_options.cacertfile=${SSL_PEM:?err}
      ssl_options.certfile=${SSL_CERTIFICATE:?err}
      ssl_options.keyfile=${SSL_KEY:?err}
      ssl_options.verify=verify_peer
      ssl_options.fail_if_no_peer_cert=true

  mysql:
    image: mariadb:10.5
    ports:
      - "3307:3306"
    restart: on-failure
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD:?err}
      MYSQL_HOST: 127.0.0.1
    healthcheck:
      test: "mysql -u${MYSQL_USER} -p${MYSQL_PASSWORD:?err} -e \"show databases\""
      interval: 1s
      retries: 120

  gateway-server:

    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - "${SSL_FILE_PATH:?err}:${SSL_FILE_PATH}"
    ports:
      - "${GATEWAY_SERVER_SSL_PORT:?err}:${GATEWAY_SERVER_SSL_PORT}"
    build: .
    environment:
      - HOST=${GATEWAY_SERVER_HOST:?err}
      - PORT=${GATEWAY_SERVER_PORT:?err}

      - SSL_PORT=${GATEWAY_SERVER_SSL_PORT:?err}
      - SSL_CERTIFICATE=${SSL_CERTIFICATE:?err}
      - SSL_KEY=${SSL_KEY:?err}
      - SSL_PEM=${SSL_PEM:?err}


      - MYSQL_HOST=mysql
      - MYSQL_USER=${MYSQL_USER:?err}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:?err}
      - MYSQL_DATABASE=${MYSQL_DATABASE:?err}
      - SOCK_PORT=${GATEWAY_SERVER_SYNC_SOCKET_PORT:?err}
      - RSA_PR_KEY=${SSL_KEY:?err}

      - MYSQL_BE_HOST=mysql
      - MYSQL_BE_PASSWORD=${MYSQL_PASSWORD:?err}
      - MYSQL_BE_DATABASE=${MYSQL_DATABASE:?err}

      - RMQ_HOST=${RMQ_HOST:-rmq}
      - RMQ_SSL=${RMQ_SSL:false}

#  sync_sockets:
#    depends_on:
#      - gateway_server
#    ports:
#      - "15001:15001"
#    build: ./sockets/
#    environment:
#      HOST: ${HOST}
#      PORT: ${PORT}
#      SOCK_PORT: ${SOCK_PORT}
#      SOCK_HOST: ${SOCK_HOST}
